name: Build & Validate

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Build 11ty
        run: npm run build

      - name: Check internal links
        run: |
          npx html-validator-cli "_site/**/*.html"

      - name: Validate HTML
        run: |
          npx html-validate "_site/**/*.html"